### ISSUE TITLE
a标签缺少href属性的情况下报错

### ISSUE THREAD

**Issue by wst7** [rowthan/whats-element#10]
实际情况：a标签缺少href属性的情况下报错

期望：a标签缺少href属性的情况下也可以拿到唯一的selector

**Comment by wst7** [comment]
提了一个PR：https://github.com/rowthan/whats-element/pull/11

**Comment by wst7** [comment]
@rowthan hi，方便的话可以同步一下npm吗

**Comment by rowthan** [comment]
> @rowthan hi，方便的话可以同步一下npm吗

version: 2.4.0
