### ISSUE TITLE
引入错误

### ISSUE THREAD

**Issue by kunkkaliu** [rowthan/whats-element#2]
import whatsElement from 'whats-element';

console.log(whatsElement);
这种方式引入是报错，whatsElement undefined

**Comment by rowthan** [comment]
> import whatsElement from 'whats-element';
> 
> console.log(whatsElement);
> 这种方式引入是报错，whatsElement undefined

源代码规范采用的es6规范，由于要发布npm包，最后export采用的CommonJS规范，可能是由此原因导致的，建议使用gulp或webpack时，使用能兼容 import、require 的导入方式。后面考虑统一使用CommonJS
