### ISSUE TITLE
有什么使用场景？

### ISSUE THREAD

**Issue by guguji5** [rowthan/whats-element#4]
为什么要为每一个DOM元素计算出可定位到它的唯一的标识符 ？

**Comment by rowthan** [comment]
我自己目前用的场景有以下：
1、标记元素，用于二次查找、快速定位（可用于基于UI的自动化测试）。这边有一个小插件用到了该仓库，（Firefox）https://addons.mozilla.org/zh-CN/firefox/addon/page-note/
[EasyShare](https://github.com/rowthan/easyshare)
2、埋点监控，可监控某一元素点击量等，用户点击图谱等。
...
终究目的是将DOM元素可描述化、能标记。其实Xpath也能做到标记元素，但使用不是很方便，并且标识符过于晦涩难懂，所以做了这么一个工具。

**Comment by guguji5** [comment]
@rowthan 哦，好棒，谢谢
