### ISSUE TITLE
对于未来元素有什么好的方案吗？

### ISSUE THREAD

**Issue by xuexb** [rowthan/whats-element#5]
比如一些弹出层，是在用户某些操作时才会触发，甚至元素的 `id`、`class` 等都是随机的，并且上下文元素都不是固定的。

这样的元素如何标识唯一呢？有空时一起讨论下哈~ 👍

**Comment by rowthan** [comment]
这种情况，理论上前一个弹出层和下一个弹出层就不是同一个DOM了。
不过对于用户来说看到的还是同一个弹窗，他们认为是同一个元素，是这样吗？

我这里有一个思路是：可以使用 like 模式，例如判断弹窗内的元素、文本是否和上一次相等来判断是否为同一个元素，不完全取决于 wid。

不过这种方法，只能用于比对前后元素，不能用于元素选取（因为是未来才会出现的元素）。

可以具体描述下使用场景、用途，看看有什么解决办法。
